[package]
name = "core"
version = "0.1.0"
edition.workspace = true

[dependencies]
hashbrown = { version = "0.15.4", features = ["serde"] }
ordered-float = { version = "5.0.0", features = ["serde"] }
ordermap = "0.5.8"
serde = { version = "1.0.219", features = ["derive"] }
