[package]
name = "logger"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
dynamorio-sys = "11.90.1"
parking_lot = "0.12.4"
logger_core = { path = "../core", package = "core" }
